COMMENTS_NATURAL = [
    "Wah keren banget kak!", "Informatif, makasih!", "Jadi pengen nyobain deh!",
    "Lucu banget! 😂", "Setuju banget sama ini!", "Mantap jiwa!",
    "Inspiratif banget postingannya", "Suka banget sama vibesnya",
    "Ga nyangka bisa serius ini", "Bermanfaat banget buat aku",
    "Bagus banget hasilnya", "Salut sama kreativitasnya",
    "Emang juara sih ini", "Ngena banget di hati",
    "Bikin ngakak tapi berfaedah", "Simple tapi kece",
    "Wajib dicoba nih", "Thank you infonya!",
    "Aku juga mau dong", "Makin semangat lihat ini",
    "Jarang-jarang ada yang kayak gini", "Penjelasannya mudah dipahami",
    "Nggak rugi deh follow", "Top markotop!",
    "Ini baru namanya konten berkualitas", "Jangan stop berkarya ya",
    "Udah lama nunggu konten kaya gini", "Cocok banget buat pemula",
    "Mudah-mudahan banyak yang lihat", "Kontennya selalu menghibur",
    "Suka banget editingnya", "Lagu di video ini apa ya?",
    "Bikin ketagihan nontonnya", "Kenapa baru muncul sekarang?",
    "Akhirnya ada yang bahas ini", "Cocok buat jadi inspirasi",
    "Kok bisa-bisanya sih?", "Ngasih semangat banget",
    "Pantesan banyak yang suka", "Gokil sih ini",
    "Lebih berguna dari pelajaran sekolah", "Aku save deh",
    "Bener banget kata-katanya", "Aku follow ya",
    "Bisa request konten nggak?", "Idola banget deh",
    "Mimpi aku pengen kayak gini", "Keren banget sudut pandangnya",
    "Ga ada obatnya emang", "Inimah level dewa",
    "Pertamax!", "Yang nggak setuju mana?",
    "Ada yang sama kayak aku nggak?", "Jadi inget masa lalu",
    "Beda dari yang lain emang", "Lagi butuh banget konten gini",
    "Ditunggu konten selanjutnya", "Makasih sharingnya ya",
    "Kok lucu banget sih?", "Bisa jadi tutorial nih",
    "Ini favorit aku banget", "Wah bisa juga ya",
    "Dari dulu suka akun ini", "Jangan lupa bahagia",
    "Senyum-senyum sendiri lihatnya", "Videonya berasa banget",
    "Gimana cara bikinnya?", "Bisa lebih detail lagi nggak?",
    "Bener kata orang, konten ini emas", "Aku tunggu info selanjutnya",
    "Lagi galau, ini menghibur", "Screenshot dulu ah",
    "Bisa juga dipraktekin", "Setiap postingan selalu bagus",
    "Bermanfaat banget buat sehari-hari", "Ini bikin hariku lebih baik",
    "Gak nyangka serame ini di komen", "Btw, salam kenal semuanya",
    "Jelasinnya enak banget", "Artinya dalem banget",
    "Ini relate banget sama aku", "Kalau bisa bikin versi lainnya",
    "Minta tips dong", "Pertahankan kualitasnya",
    "Ini beneran lho, keren", "Apa kabar semuanya?",
    "Lagi rame ya di sini", "Jadi makin cinta konten begini",
    "Bakal booming ini mah", "Mantul!",
    "Kalau gini terus aku jadi ketagihan", "Sumpah, jadi nostalgia",
    "Jangan di-skip ya videonya", "Sederhana tapi berkelas",
    "Bikin aku berpikir ulang", "Salut deh pokoknya",
    "Lanjuuutkan!", "Respect!",
    "Ini konten juara", "Makasih ya udah berbagi"
]

COMMENTS_PROMOSI = [
    "Eh ada acara seru loh di IG ini, coba cek deh! ",
    "Ngomongin soal ini, aku nemu yang lebih keren lho ",
    "Sst.. jangan bilang siapapun, tapi aku punya rekomendasi buat kamu ",
    "Btw, kalian tau nggak sih akun ? Keren banget!",
    "Jangan lupa mampir ya, ada info penting nih di bio aku",
    "Buat yang penasaran, cek aja langsung!",
    "Ada yang baru nih, buruan cek sebelum kehabisan!",
    "Wah aku jadi ingat sesuatu yang cocok banget sama ini",
    "Tahu nggak? Ada kejutan menarik lho sekarang",
    "Eh serius deh, kalian wajib tahu info yang satu ini",
    "Kalau suka yang kayak gini, aku punya yang lebih mantap",
    "Nggak percaya? Buktikan sendiri aja",
    "Udah pada tau belum? Ada yang baru lagi nih",
    "Ini sih belum seberapa dibanding yang aku tahu",
    "Mau yang lebih seru? Merapat yuk!",
    "Yang penasaran, langsung kepoin aja",
    "Jangan sampe ketinggalan ya!",
    "Btw, ada yang mau aku kasih tahu nih",
    "Cusss cek sekarang sebelum telat",
    "Banyak yang tanya, akhirnya aku spill juga",
    "Aku biasanya sih gini, kalian coba deh",
    "Ngomong-ngomong, ada info bagus lho",
    "Ini mah cuma contekan, aslinya lebih mantap",
    "Awas ketinggalan info terbaru!",
    "Ada yang spesial nih buat kamu",
    "Yang mau diskusi lebih lanjut, langsung aja ya",
    "Ini bikin penasaran kan? Lihat aja sendiri",
    "Udah aku buktiin, sekarang giliran kamu",
    "Kuncinya ada di sini, tonton sampai habis",
    "Jangan bilang-bilang, ada give away seru",
    "Kapan lagi bisa dapetin ini?",
    "Buruan ikutan, menang banyak!",
    "Ada yang bisa nebak? Cek di bio aja",
    "Ini dia yang ditunggu-tunggu",
    "Ada bocoran nih buat kalian",
    "Sebelum terlambat, mending langsung cek",
    "Terbatas banget lho kesempatannya",
    "Khusus hari ini aja ada diskon",
    "Yang mau hemat, wajib tahu ini",
    "Dari kemarin rame bahas ini, yuk ikutan",
    "Mumpung masih ada, langsung sikat!",
    "Jangan cuma lihat, buktikan sendiri",
    "Ini jawaban dari penasaran kalian",
    "Akhirnya ketemu juga yang cocok",
    "Rekomendasi terbaik buat kamu",
    "Ini pengalaman aku, mungkin berguna buat kalian",
    "Spill dong, ada yang tahu lebih?",
    "Ini sih favorit aku banget",
    "Mau tahu rahasia di balik ini?",
    "Pas banget buat yang lagi nyari inspirasi",
    "Kok baru tahu sekarang? Langsung cek!",
    "Serius, ini mengubah pandangan aku",
    "Jangan di-skip, ini penting!",
    "Ini worth it banget buat dicoba",
    "Mau info lengkap? DM aja ya",
    "Jangan lupa pantau terus update-nya",
    "Ini bisa jadi solusi buat kalian",
    "Nyesel kalau nggak ikutan",
    "Siapa tahu ini yang kamu butuhkan",
    "Yakin nggak mau coba?",
    "Aku aja udah, kamu kapan?",
    "Dari sekian banyak, ini yang paling oke",
    "Pusing cari referensi? Ini jawabannya",
    "Biar nggak kudet, buruan cek",
    "Satu klik aja, hidupmu berubah",
    "Nggak akan rugi deh",
    "Mau yang lebih praktis? Ini dia",
    "Terbukti ampuh, cobain yuk",
    "Ini dia yang bikin aku ketagihan",
    "Aku spill dikit ya, sisanya cek sendiri",
    "Banyak yang salah, ini yang benar",
    "Udah banyak yang buktiin, kamu kapan?",
    "Rame banget, sampe trending lho",
    "Segini dulu ya, kepanjangan nanti",
    "Boleh dong sharing pengalaman juga",
    "Yang setuju komen ya, yang belum coba wajib cek",
    "Ini game changer banget",
    "Seneng bisa share ini ke kalian",
    "Yuk ramein, jangan malu-malu",
    "Aku pribadi sih rekomen banget",
    "Siapa tahu cocok, coba aja dulu",
    "Gagal move on dari ini",
    "Kalau ada yang lebih baru, kabari ya",
    "Nggak nyesel deh pokoknya",
    "Sekali coba langsung jatuh cinta",
    "Ini mah udah level dewa",
    "Bener-bener di luar ekspektasi",
    "Aku kasih rating 10/10",
    "Bisa request lagi nggak?",
    "Yang nggak percaya, buktikan saja",
    "Ada diskon spesial nih, cepetan!",
    "Serius, ini hidden gem banget",
    "Nyesel nggak dari kemarin",
    "Ayo buruan, mumpung lagi promo",
    "Ini jawaban doa aku",
    "Wajib coba minimal sekali seumur hidup",
    "Kalau nggak sekarang, kapan lagi?",
    "Langka banget ini, susah dicari",
    "Udah gitu aja dulu, next aku spill lagi"
]
